### ISSUE TITLE
strided tiles (RFC)

### ISSUE THREAD

**Issue by xalexalex** [qupath/qupath-extension-wsinfer#46]
Simply a request for comments.

In my experience I often find strided inference (i.e. overlapping tiles) to be more informative than inference on a grid of non-overlapping tiles, like WSInfer and its qupath extension currently do. This could be not-too-hard to implement in the wsinfer window.

I don't know if this requires changes on the WSInfer backend (I think not), however I have no idea how QuPath handles overlapping detections.

**Comment by kaczmarj** [comment]
i think adding this is a great idea overlapping tiles could give us smoother heatmaps and maybe would smooth out some noisy classifications.

this would require a change in this repo (for the qupath extension) and in the wsinfer python repo (i opened https://github.com/SBU-BMI/wsinfer/issues/202 to track this).

i'm not sure how to structure the outputs of overlapping tiles. would we do any sort of averaging across overlaps? or would we use the small non-overlapping regions and make those the patches that we visualize?

**Comment by petebankhead** [comment]
This should already be possible in QuPath if you generate the tiles with *Analyze &rarr; Tiles & superpixels &rarr; Create tiles*.

There is some [more information here](https://qupath.readthedocs.io/en/0.4/docs/deep/wsinfer.html#create-or-select-an-annotation). The 'select tiles' option is there to make the command really flexible.

> I don't know if this requires changes on the WSInfer backend (I think not), however I have no idea how QuPath handles overlapping detections.

When using the QuPath extension there isn't really a WSInfer backend. The QuPath WSInfer extension only uses WSInfer models & specification - all the code in the extension is specific to QuPath, using PyTorch via Deep Java Library (but not involving Python at all).
