### ISSUE TITLE
Handling out-of-bounds coordinate requests

### ISSUE THREAD

**Issue by alanocallaghan** [qupath/qupath-extension-wsinfer#9]
WSInfer seems to handle incorrectly-sized tiles okayish, based on the fact that I originally had `trimToRoi` set rather than `trimToROI`, meaning that the tiler plugin was using the default. This results in some smaller tiles as they're trimmed to the tile boundary.

Based on that I'd tend to submit smaller tiles when `x + width >= server.getWidth() || y + height >= server.getHeight()`. When `x < 0 || y < 0` and `!(x + width >= server.getWidth() || y + height >= server.getHeight())` then I guess do similarly

https://github.com/qupath/qupath-extension-wsinfer/blob/b261aec38d892a83b07bca0e6a5adfbb261339f7/src/main/java/qupath/ext/wsinfer/TileLoader.java#L107

**Comment by petebankhead** [comment]
Addressed by https://github.com/qupath/qupath-extension-wsinfer/pull/24/commits/398cd41c09410b0566346087e47efb6c893a2ae0

It just uses padding (zero-padding... I think :/ ) so nothing terribly clever.
